import frappe
from frappe.utils import now_datetime

from agent_incentives.agent_incentives.services.calculation import build_run_rows


CALCULATION_VERSION = "phase2-v0.1"


@frappe.whitelist()
def calculate_run(run_name, force_rebuild=False):
    frappe.only_for(("System Manager",))
    run = frappe.get_doc("Agent Incentive Run", run_name)
    if run.status == "Locked":
        frappe.throw("Locked runs cannot be recalculated.")

    existing = frappe.get_all(
        "Agent Incentive Ledger",
        filters={"incentive_run": run.name},
        pluck="name",
    )
    if existing and not frappe.utils.cint(force_rebuild):
        frappe.throw("Ledger rows already exist for this run. Use force_rebuild=1 to rebuild draft rows.")

    for row_name in existing:
        frappe.delete_doc("Agent Incentive Ledger", row_name, force=1, ignore_permissions=True)

    rows = build_run_rows(run.company, run.period_start, run.period_end)

    total_payout = 0
    for row in rows:
        doc = frappe.get_doc({
            "doctype": "Agent Incentive Ledger",
            "incentive_run": run.name,
            "company": run.company,
            "agent_user": row["agent_user"],
            "agent_name": row["agent_name"],
            "period_start": run.period_start,
            "period_end": run.period_end,
            "gross_collected": row["gross_collected"],
            "credit_note_amount": row["credit_note_amount"],
            "net_collected": row["net_collected"],
            "threshold_amount": row["threshold_amount"],
            "eligible_amount": row["eligible_amount"],
            "incentive_percentage": row["incentive_percentage"],
            "payout_amount": row["payout_amount"],
            "adjustment_amount": 0,
            "plan_reference": row["plan_reference"],
            "approval_status": "Draft",
            "payment_status": "Unpaid",
            "remarks": "Generated by Phase 2 calculation engine",
        })
        doc.insert(ignore_permissions=True)
        total_payout += float(row["payout_amount"] or 0)

    run.status = "Calculated"
    run.run_on = now_datetime()
    run.triggered_by = frappe.session.user
    run.calculation_version = CALCULATION_VERSION
    run.row_count = len(rows)
    run.total_payout_amount = total_payout
    run.exception_count = 0
    run.save(ignore_permissions=True)

    return {
        "ok": True,
        "run": run.name,
        "rows_created": len(rows),
        "total_payout_amount": total_payout,
        "calculation_version": CALCULATION_VERSION,
    }
